### ISSUE TITLE
Translation to Dutch 

### ISSUE THREAD

**Issue by JerryOow** [MicrosoftDocs/SCCMDocs.nl-nl#3]
[I would like to make some corrections about the translation from eng to nl]

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: cb5de8cb-c607-433d-7f6e-0d47b346195d
* Version Independent ID: 513164f1-2959-9584-e8af-018957512633
* Content: [Windows installeren op een nieuwe computer - Configuration Manager](https://docs.microsoft.com/nl-nl/sccm/osd/deploy-use/install-new-windows-version-new-computer-bare-metal#feedback)
* Content Source: [sccm/osd/deploy-use/install-new-windows-version-new-computer-bare-metal.md](https://github.com/Microsoft/SCCMDocs-pr.nl-nl/blob/live/sccm/osd/deploy-use/install-new-windows-version-new-computer-bare-metal.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by CeciAc** [comment]
Hi @JerryOow
You can create a Pull Request with your linguistic suggestions by clicking here:
![imagen](https://user-images.githubusercontent.com/26746247/48714728-131bc480-ebf2-11e8-932c-374c312535b0.png)

Thank you for your feedback. The page in question has been machine-translated, which is not always perfectly understandable. We recently added a "Read in English" option on the right which allows you to switch to the English version without having to change the language settings.

Kind regards,
Microsoft DOCS International Team
